import { expect, test } from '@playwright/test'

const admin = { username: 'root_admin', password: 'admin-pass-1' }
const memberA = { username: 'member_a', password: 'member-pass-1' }
const memberB = { username: 'member_b', password: 'member-pass-1' }
const memberReset = { username: 'member_reset', password: 'member-pass-1' }

async function waitForAuthReady(page: import('@playwright/test').Page): Promise<void> {
  await expect(page.locator('[data-auth-ready="true"]')).toBeVisible()
}

async function login(page: import('@playwright/test').Page, account: { username: string; password: string }): Promise<void> {
  await page.goto('/login')
  await waitForAuthReady(page)
  await page.getByLabel('用户名').fill(account.username)
  await page.getByLabel('密码').fill(account.password)
  const response = page.waitForResponse((value) => value.url().includes('/api/auth/login') && value.request().method() === 'POST')
  await page.getByRole('button', { name: '登录' }).click()
  const loginResponse = await response
  expect(loginResponse.status()).toBe(200)
  await expect.poll(async () => (await page.context().cookies()).some((item) => item.name === '__Host-ppt_session')).toBe(true)
  expect((await page.request.get('/api/auth/session')).status()).toBe(200)
}

async function register(page: import('@playwright/test').Page, account: { username: string; password: string }): Promise<void> {
  await page.goto('/register')
  await waitForAuthReady(page)
  await page.getByLabel('用户名').fill(account.username)
  await page.getByLabel('密码', { exact: true }).fill(account.password)
  await page.getByLabel('确认密码').fill(account.password)
  const response = page.waitForResponse((value) => value.url().includes('/api/auth/register') && value.request().method() === 'POST')
  await page.getByRole('button', { name: '提交注册' }).click()
  expect((await response).status()).toBe(201)
  await expect(page.getByRole('heading', { name: '注册已提交' })).toBeVisible()
}

async function expectChineseAuthSurface(page: import('@playwright/test').Page, title: string): Promise<void> {
  await expect(page).toHaveTitle(title)
  await expect(page).not.toHaveTitle(/CUNY|email/i)
  await expect(page.locator('input[type="email"]')).toHaveCount(0)
}

test('P15 registers, awaits approval, logs in, creates a private Presentation, exports, and logs out on desktop and mobile', async ({ page, browser }) => {
  await page.goto('/')
  await expect(page).toHaveURL(/\/login/)
  await waitForAuthReady(page)
  await expectChineseAuthSurface(page, '登录 · 模板资产库')
  await page.goto('/change-password')
  await expect(page).toHaveURL(/\/login/)
  await waitForAuthReady(page)
  await page.getByLabel('用户名').fill('unknown_user')
  await page.getByLabel('用户名').focus()
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('密码')).toBeFocused()
  await page.getByLabel('密码').fill('incorrect-password')
  await page.getByRole('button', { name: '登录' }).click()
  const loginError = page.getByRole('alert')
  await expect(loginError).toHaveText('用户名或密码不正确。')
  await expect(loginError).toBeFocused()
  await page.getByRole('link', { name: '注册' }).click()
  await waitForAuthReady(page)
  await expectChineseAuthSurface(page, '注册 · 模板资产库')
  await page.getByLabel('用户名').fill(memberA.username)
  await page.getByLabel('密码', { exact: true }).fill(memberA.password)
  await page.getByLabel('确认密码').fill(memberA.password)
  const registerA = page.waitForResponse((response) => response.url().includes('/api/auth/register') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '提交注册' }).click()
  expect((await registerA).status()).toBe(201)
  await expect(page.getByRole('heading', { name: '注册已提交' })).toBeVisible()
  await expectChineseAuthSurface(page, '等待审批 · 模板资产库')

  const second = await browser.newPage({ viewport: { width: 390, height: 844 } })
  await second.goto('/register')
  await waitForAuthReady(second)
  await second.getByLabel('用户名').fill(memberB.username)
  await second.getByLabel('密码', { exact: true }).fill(memberB.password)
  await second.getByLabel('确认密码').fill(memberB.password)
  const registerB = second.waitForResponse((response) => response.url().includes('/api/auth/register') && response.request().method() === 'POST')
  await second.getByRole('button', { name: '提交注册' }).click()
  expect((await registerB).status()).toBe(201)
  await expect(second.getByRole('heading', { name: '注册已提交' })).toBeVisible()
  await second.close()

  await login(page, admin)
  await expect(page.getByText('你好，root_admin')).toBeVisible()
  await page.getByRole('link', { name: '账号审批' }).click()
  await expect(page.getByRole('heading', { name: '账号审批' })).toBeVisible()
  await expectChineseAuthSurface(page, '账号审批 · 模板资产库')
  for (const username of [memberA.username, memberB.username]) {
    const row = page.locator('tr', { hasText: username })
    await row.getByRole('button', { name: '批准' }).click()
  }
  const mobileAdmin = await browser.newPage({ viewport: { width: 390, height: 844 } })
  await login(mobileAdmin, admin)
  await mobileAdmin.getByRole('link', { name: '账号审批' }).click()
  await expect(mobileAdmin.getByRole('heading', { name: '账号审批' })).toBeVisible()
  await expect(mobileAdmin.getByRole('button', { name: '退出' })).toBeVisible()
  expect(await mobileAdmin.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await mobileAdmin.close()
  await page.getByRole('button', { name: '退出' }).click()
  await expect(page).toHaveURL(/\/login/)

  await login(page, memberA)
  await expect(page.getByText('你好，member_a')).toBeVisible()
  await expect(page.getByRole('heading', { name: '备份与恢复演练' })).toHaveCount(0)
  await page.getByLabel('新汇报名称').fill('P15 私人汇报')
  const created = page.waitForResponse((response) => response.url().includes('/api/presentations') && response.request().method() === 'POST' && response.status() === 201)
  await page.getByRole('button', { name: '创建汇报' }).click()
  const presentation = await (await created).json() as { presentation: { id: string } }
  await page.getByRole('button', { name: '加入所选模板' }).click()
  await page.getByRole('button', { name: '生成 HTML/ZIP' }).click()
  await expect(page.getByText(/已生成离线 HTML\/ZIP/)).toBeVisible()
  await expect(page.getByRole('link', { name: 'ZIP' }).first()).toBeVisible()

  const b = await browser.newPage({ viewport: { width: 390, height: 844 } })
  await login(b, memberB)
  await expect(b.getByText('你好，member_b')).toBeVisible()
  await expect(b.getByText('P15 私人汇报')).toHaveCount(0)
  const other = await b.request.get(`/api/presentations/${presentation.presentation.id}`)
  expect(other.status()).toBe(404)
  expect(await b.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await b.close()

  await page.getByRole('button', { name: '退出' }).click()
  await expect(page).toHaveURL(/\/login/)
  expect((await page.request.get('/api/auth/session')).status()).toBe(401)
})

test('P15 resets an independently approved member, forces password change, and invalidates the old session', async ({ page, browser }) => {
  await register(page, memberReset)
  await login(page, admin)
  await page.getByRole('link', { name: '账号审批' }).click()
  const approval = page.locator('tr', { hasText: memberReset.username })
  await approval.getByRole('button', { name: '批准' }).click()
  const oldSession = await browser.newPage()
  await login(oldSession, memberReset)
  await expect(oldSession.getByText('你好，member_reset')).toBeVisible()
  const row = page.locator('tr', { hasText: memberReset.username })
  await row.getByRole('button', { name: '重置密码' }).click()
  const temporary = await page.locator('.temporary code').textContent()
  expect(temporary).toMatch(/^[A-Za-z0-9_-]{24}$/)
  expect((await oldSession.request.get('/api/auth/session')).status()).toBe(401)
  await oldSession.close()
  await page.getByRole('button', { name: '退出' }).click()
  await login(page, { username: memberReset.username, password: temporary ?? '' })
  await expect(page.getByRole('heading', { name: '请修改临时密码' })).toBeVisible()
  await waitForAuthReady(page)
  await expectChineseAuthSurface(page, '修改密码 · 模板资产库')
  await expect(page.getByRole('heading', { name: '模板资产库' })).toHaveCount(0)
  const old = await browser.newPage()
  await old.goto('/login')
  await waitForAuthReady(old)
  await old.getByLabel('用户名').fill(memberReset.username)
  await old.getByLabel('密码').fill(memberReset.password)
  await old.getByRole('button', { name: '登录' }).click()
  await expect(old.getByRole('alert')).toHaveText('用户名或密码不正确。')
  await old.close()
  await page.getByLabel('当前密码').fill(temporary ?? '')
  await page.getByLabel('新密码', { exact: true }).fill('new-reset-pass-1')
  await page.getByLabel('确认新密码').fill('new-reset-pass-1')
  await page.getByRole('button', { name: '修改密码' }).click()
  await expect(page).toHaveURL(/\/login/)
  expect((await page.request.get('/api/auth/session')).status()).toBe(401)
  await login(page, { username: memberReset.username, password: 'new-reset-pass-1' })
  await expect(page.getByText('你好，member_reset')).toBeVisible()
})
