export const INTERACTIVE_TEMPLATE_V2_ALLOWLIST = [
  // P01 repository-local protocol fixture.
  'fb0e964ed926db0c20bb1706044db6e1c52b5ee65dea7d20ae0a3699611e1490',
  // P05 reviewed repository-local production-ID fixture packages (generated by fixtures/p05-interactive-v2/generator.ts).
  // Keep the previous fixture digests readable for already-registered historical versions.
  '69c50aa987f19eee64a8c84f698cb28f220a3f4e824276d6a85f7c388ba5e550',
  '89a4a6378b47c04cfdf9c5777eaf35e0b41ad23f4ac2da6e0f56f6b68cbca0ca',
  '351ac129cd4971824a2c5bf7092373ad504dec5d37ce2ed8a8b82cf13f2df952',
  'f81dd38790c87e81901bb6ddb76246132f7ab08d2da6864c43a0572e653e62da',
  '9b38a428a0c90b7f947e320f2f0ce7a12b52aef8be2b4e1a2411f3f0b07da929',
  'd8b06d0b0057539e6932a216e24344c20b21a3ee183603b5be6e47ef0efe2bd1',
  '3c0d186d87dea0b7ff4160ed427c088c8077e615a9fcfee2e125520bbfa43bc7',
  '58d77252498cba51cc27d05e11964ac45aaefcbecf2082cca926f0e3931036a9',
  '45e914c9caa704b144fa31192c2f3b7a4278d15aff315a6e7f439bdf12d11349',
  '1a3cc8c2e4609fc177ac7c44cac73c96d524a18d3888185ead0be5a22dbe15b2',
  '59e352797e3f7ef26232b5b8cec93b8f49240221d45b7be916a7daa9fa8771dd',
  'f5e7789a8e5389a05eecd6c3385dca5610a1ac00a7a0b78238b454d8ef822c00',
  // Production-metadata-aligned replacements for the 12 importable v2 packages.
  '6ff375625d49b4f71060eb994964f7f69fbef8c1a913aafba3dc4d31b5e03618',
  '3fa4eb24116c8bfed1bf269b5f8b7a51bb7deec377cbdd0a7d60f11a435f27fd',
  'cf73e6bd4e05f1548f8b95c609f88aca7bf5e93615aa529acaa6cffeb4e61049',
  'b5dc771ee66ac955d7950b8da57abc59743c9fe211c52fa1ea701ca5b9f7d5c6',
  '5ad8b833fff641e0c57e582ba4a393c4eafb5fd617ed8454c78388ed588fa5d2',
  '3c7b091a0e7ef7288c5a168c5e1635e62ef3edebb070baeb146f9c0acbe55ed7',
  'a81cca00a218312149450197c3dc90e533bca2088e84a7ee5a8026ed5bec7a07',
  'a517824d6c33083b18beac521ae1d3cf660d2446c0c6683b1db64ed5f9cb32c7',
  '78568b757e055c5a038a18ec566090ffae56be245d48a2bbbe2f39cc1cbb4143',
  'e7e314e1bfbab5d828846674638857afd954a978850564a2d5c18984ee2b2229',
  '7c6ef1707f4cfccd1ea9f0d9e025f74df41b5f0625e99807928db2c206f93104',
  '8d083f34c9667ad05b038fb533eb0b560a588d9a557074d1be9ebff67e401330',
] as const

const approvedDigests = new Set<string>(INTERACTIVE_TEMPLATE_V2_ALLOWLIST)

export function isAllowlistedInteractiveTemplateDigest(digest: string): boolean {
  return /^[0-9a-f]{64}$/.test(digest) && approvedDigests.has(digest)
}
