export const INTERACTIVE_TEMPLATE_V2_ALLOWLIST = [
  // P01 repository-local protocol fixture.
  'fb0e964ed926db0c20bb1706044db6e1c52b5ee65dea7d20ae0a3699611e1490',
  // P05 reviewed repository-local fixture packages (generated by fixtures/p05-interactive-v2/generator.ts).
  '428e873b013ded899216b14c761dad2535806e441358e3ac60a51fbf8a934fd2',
  '9e52502a590a269b31a92f019b5e74d3691b57b8b1b6420913e9fd83d196d6bc',
  '9abdbb38938d616c133c4c3c470ee9812bf4192e7caaeb8e063da4e2f46fcf29',
  '6b51076c952945a822419b4d30e697ea2579af59249d94272c612643d4675e05',
  '78fed1e5b4be11733bc7c44d949291718e80461ba4a85d14798a334ed28c6b75',
  '57fd5371b64ab75527979e05dde02407b5613329c9127ef23fdf873437983cc3',
  '5b4a51f8932a822085de3b6a26d10196f5673b0dd1e03a8a8aa2e46f2b1242de',
  '61705cb5a2d5dd725182b17f0c58b0e22d58a34e4a4f1cc81d0ee2b87f2e08d6',
  '0bb7388a55a45883e02d32d31183ff7c266b57a7394384aff7fabf517f30426e',
  '15ebba3621917ae6c9fd3a7323eaf658b606af5a78de31341ac23b4d7b5ad5d4',
  '4e3d0d3d3260146d114d437d51648e5b4bc34a65e9686d01fd162b57dd482942',
  '54881905898e48c503d4772a1dffb7593087ddd12596409042c5ec0c99238587',
] as const

const approvedDigests = new Set<string>(INTERACTIVE_TEMPLATE_V2_ALLOWLIST)

export function isAllowlistedInteractiveTemplateDigest(digest: string): boolean {
  return /^[0-9a-f]{64}$/.test(digest) && approvedDigests.has(digest)
}
