export const INTERACTIVE_TEMPLATE_V2_ALLOWLIST = [
  // P01 repository-local protocol fixture.
  'fb0e964ed926db0c20bb1706044db6e1c52b5ee65dea7d20ae0a3699611e1490',
  // P05 reviewed repository-local production-ID fixture packages (generated by fixtures/p05-interactive-v2/generator.ts).
  '69c50aa987f19eee64a8c84f698cb28f220a3f4e824276d6a85f7c388ba5e550',
  '89a4a6378b47c04cfdf9c5777eaf35e0b41ad23f4ac2da6e0f56f6b68cbca0ca',
  '351ac129cd4971824a2c5bf7092373ad504dec5d37ce2ed8a8b82cf13f2df952',
  'f81dd38790c87e81901bb6ddb76246132f7ab08d2da6864c43a0572e653e62da',
  '9b38a428a0c90b7f947e320f2f0ce7a12b52aef8be2b4e1a2411f3f0b07da929',
  '7b1ef0d8c1bd28d4529d005ed0eb08fc566ef9cf00c02e94440bf33bb709a816',
  '2d314754bb9475634a66900a3c2aa6d0b7ac08cb39d9b659487627dd2ea0a707',
  '58d77252498cba51cc27d05e11964ac45aaefcbecf2082cca926f0e3931036a9',
  '45e914c9caa704b144fa31192c2f3b7a4278d15aff315a6e7f439bdf12d11349',
  '1a3cc8c2e4609fc177ac7c44cac73c96d524a18d3888185ead0be5a22dbe15b2',
  '59e352797e3f7ef26232b5b8cec93b8f49240221d45b7be916a7daa9fa8771dd',
  'd8357a308755fd156ec4cec5a38cf5d8048e997dda20fb103aba51437f389e04',
] as const

const approvedDigests = new Set<string>(INTERACTIVE_TEMPLATE_V2_ALLOWLIST)

export function isAllowlistedInteractiveTemplateDigest(digest: string): boolean {
  return /^[0-9a-f]{64}$/.test(digest) && approvedDigests.has(digest)
}
